---
framework: jest
postMerge:
  isActive: true 
  pattern:
    - "./test/*.js"
  env: 
    NODE_ENV: test
  strategy:
    threshold: 4
    name: after_n_commits
preMerge:
  pattern:
    - "./test/*.js"
  env: 
    NODE_ENV: test
preRun:
     command:
        - yarn install --immutable
        - yarn run build
postRun:
     command:
        - yarn --version
version: 1.0
