---
framework: jest
tier: xsmall
postMerge:
  pattern:
    - "./test/*.test.js"
preMerge:
  pattern:
    - "./test/*.test.js"
preRun:
     command:
        - yarn install
        - yarn run build
postRun:
     command:
        - yarn --version
version: 2.1
