---
framework: jest
postMerge:
  pattern:
    - "./test/*.js"
  env: 
    NODE_ENV: test
preMerge:
  pattern:
    - "./test/*.js"
  env: 
    NODE_ENV: test
preRun:
     command:
        - yarn install --immutable
        - yarn run build
postRun:
     command:
        - yarn --version
version: 1.0
